c_general = ["general_first_join","general_use_portal","general_first_game","general_first_chat","general_youtuber","general_first_friend","general_first_party","general_friends_25","general_creeperbook","general_vip","general_vip_plus","general_a_long_journey_begins","general_achievement_npc","general_treasure_hunt","general_hot_potato"]
t_general = [("general_coins",250000),("general_wins",2500),("general_quest_master",250),("general_challenger",500)]

c_housing = ["housing_join_guild","housing_join_friend","housing_join_staff","housing_join_youtube","housing_become_resident","housing_give_cookie","housing_new_look","housing_recieve_cookie","housing_join_random","housing_make_resident","housing_grand_opening"]
t_housing = []

c_arcade = ["arcade_pig_fishing_super_bacon","arcade_throw_out_powerup_kill","arcade_trampolinio_red_wool","arcade_bounty_hunter_target_killer","arcade_dragon_killer","arcade_hoehoehoe_score","arcade_world_economics","arcade_creeper_attack_survival","arcade_creeper_attack_iron_golem","arcade_untouchable","arcade_over_here","arcade_farm_hunt_disguise","arcade_creeper_attack_waves","arcade_savage","arcade_mini_hunter","arcade_woops_didnt_mean_to","arcade_overpowered","arcade_gotta_catch_them_all","arcade_party_games_stars","arcade_no_mercy","arcade_giddy_up_horsey","arcade_animal_slaughter","arcade_professional_mower","arcade_team_slayer","arcade_cant_hide_from_me","arcade_zombies_feels_good","arcade_hide_and_seek_prop","arcade_zombies_team_player","arcade_zombies_electrician","arcade_hide_and_seek_prop_hunter","arcade_hide_and_seek_party_pooper","arcade_zombies_ultimate","arcade_avalance_waves","arcade_creeper_attack_upgrades","arcade_rpg_16_rocket_pig","arcade_shooting_range_explosive_arrow","arcade_no_mutiny_today","arcade_dragon_slayer","arcade_dragontamer","arcade_zombies_speed_runner","arcade_zombies_win","arcade_zombies_perk_hoarder","arcade_hole_finals","arcade_pixel_painters_one","arcade_zombies_herobrine","arcade_zombies_time_trial_blood","arcade_zombes_serial_killer","arcade_mini_walls_last_man","arcade_hypixel_says_master","arcade_zombies_survivor","arcade_zombies_time_trial_dead","arcade_hole_score","arcade_dragon_wars_blast","arcade_mini_walls_damage","arcade_farm_hunt_killer","arcade_football_five_goals","arcade_football_speed","arcade_lone_survivor","arcade_ctw_i_can_be_anything","arcade_ctw_ninja","arcade_ctw_no_need","arcade_ctw_comeback","arcade_ctw_first","arcade_ctw_mvp","arcade_ctw_fashionably_late","arcade_ctw_magician","arcade_ctw_hey_there","arcade_ctw_right_place_right_time","arcade_ctw_safety_is_an_illusion",]
t_arcade = [("arcade_team_work",55),("arcade_arcade_winner",2000),("arcade_zombie_killer",2000),("arcade_miniwalls_winner",250),("arcade_football_pro",250),("arcade_bounty_hunter",3500),("arcade_arcade_banker",300000),("arcade_farmhunt_dominator",250),("arcade_zombies_round_progression",25),("arcade_hide_and_seek_hider_kills",250),("arcade_zombies_nice_shot",7500),("arcade_zombies_high_round",50),("arcade_ctw_oh_sheep",200),("arcade_ctw_slayer",1000)]

c_walls = ["walls_first_kit","walls_first_perk","walls_berserk","walls_vampirism","walls_revenge","walls_catch_fish","walls_kill_cliff","walls_starter_kits","walls_craft_flint","walls_craft_boat","walls_no_team_deaths","walls_canadian_kit","walls_engineer","walls_get_diamond_sword","walls_create_portal","walls_ride_horse","walls_customized","walls_robin_hood","walls_finding_nemo","walls_true_power","walls_burning","walls_sole_survivor","walls_untouchable","walls_record_label","walls_not_today","walls_not_a_fish","walls_ten_kills","walls_wiped_out",]
t_walls = [("walls_kills",2500),("walls_wins",500),("walls_coins",75000),("walls_diamond_miner",150)]

c_paintball = ["paintball_no_killstreaks","paintball_unlock_killstreaks","paintball_unlock_hat","paintball_combo","paintball_activate_leeroy_jenkins","paintball_activate_killstreaks","paintball_first_kill","paintball_last_kill","paintball_activate_plus_ten","paintball_hacker","paintball_admin_hat","paintball_endurance","paintball_how_does_it_feel","paintball_god_killer","paintball_trigger_happy","paintball_energy_drink","paintball_thunder_struck","paintball_on_the_brink_of_defeat","paintball_shaky_hands","paintball_undercover_sloth","paintball_cheating_death","paintball_at_least_i_tried","paintball_closure","paintball_warfare_time","paintball_do_i_get_my_nuke_now","paintball_jackson_pollock","paintball_sarcrifice","paintball_sampling","paintball_espionage","paintball_go_home_youre_drunk","paintball_now_you_see_me","paintball_lights_out","paintball_explosive_death","paintball_godfather"]
t_paintball = [("paintball_wins",2000),("paintball_kills",100000),("paintball_coins",75000),("paintball_invincible",3600),("paintball_kill_streaks",10000),("paintball_hat_collector",21)]

achs = [(c_general,t_general,"Max General"),(c_housing,t_housing,"Max Housing"),(c_arcade,t_arcade,"Max Arcade"),(c_walls,t_walls,"Max Walls"),(c_paintball,t_paintball,"Max Paintball")]

# Missing Games:
# Arena Quake VampireZ TKR Skyblock Seasonal TNT Blitz MegaWalls CVC UHC Warlords Skywars Smash SpeedUHC Bedwars MurderMystery BuildBattle Duels Pit
# 293 / 2308

c_legacy = ["arcade_ptb_ride_bat","general_gifting"]
